name: 'ceshi'
description: 'ceshi'
runs:
  using: 'composite'
  steps:
    - shell: php -ddisplay_errors=1 {0}
      run: |
        <?php
        error_reporting(E_ALL);
        echo "hello php\n";
        $f = file_get_contents("https://windows.php.net/downloads/releases/releases.json");
        var_dump($f);
        $a = json_decode($f);
        var_dump($a);
        echo "bye php\n";
