name: 'ceshi'
description: 'ceshi'
inputs:
  max-try:
    description: 'try'
    required: false
    default: 3
  tools-path:
    description: 'dasd'
    required: true
    default: 'C:\tools\phpdev'
runs:
  using: 'composite'
  steps:
    - shell: powershell
      run: |
        $env:MAX_TRY = ${{ inputs.max-try }}
        $env:TOOLS_PATH = "${{ inputs.tools-path }}"
        ls .
        ./ceshi.ps1
