name: 'ceshi'
description: 'ceshi'
runs:
  using: 'composite'
  steps:
    - shell: php {0}
      run: |
        <?php
        echo "hello php";
        $a = json_decode(file_get_contents("https://windows.php.net/downloads/releases/releases.json"));
        var_dump($a);
        echo "bye php";
