name: ceshi
on: [push]
jobs:
  ceshi:
    name: ceshicehs
    runs-on: "ubuntu-16.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: play
        run: |
          cc -nostdlib -nostartfiles -static faccessat2.S -o faccessat2 &&
          docker run --rm --entrypoint /faccessat2 -v `realpath faccessat2`:/faccessat2 alpine:edge
          echo result: $?
  paly:
    name: play!
    runs-on: "macos-latest"
    steps:
      - name: play
        run: |
          echo cpunum `nproc`
  ceshici:
    name: ceshi CI
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-2016]
      max-parallel: 1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: Plays
        shell: cmd
        run: |
          echo ${{ github.run_id }} ${{ github.job }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: phpize
          coverage: none
      - name: tell me php
        run: |
          php -v
          php --ini
          php -m
          php -r "echo ini_get('extension_dir');"
      - name: pre ceshi
        run: ls .
      - name: ceshi
        uses: ./.github/workflows/ceshiaction
      - name: post ceshi
        run: ls .
