name: ceshi
on: [push]
jobs:
  ceshici:
    name: ceshi CI
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: phpize
          coverage: none
      - name: tell me php
        run: |
          php -v
          php --ini
          php -m
          php -r "echo ini_get('extension_dir');"
      - name: pre ceshi
        run: ls .
      - name: ceshi
        uses: ./.github/workflows/ceshiaction
      - name: post ceshi
        run: ls .
