name: ceshi

on: [create]

jobs:
  ceshi:
    name: ceshi
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
      max-parallel: 1
    steps:
      - name: ceshi
        run: |
          echo $GITHUB_REF
      
